name:           process-sim
synopsis:       A simulation environment for communicating processes
maintainer:     Stanislav Moiseev <stanislav.moiseev@gmail.com>
copyright:      (C) 2018 Stanislav Moiseev

extra-source-files:
  - README.md

dependencies:
  - ansi-terminal
  - base >= 4.7 && < 5
  - containers
  - free
  - transformers
  - random
  - time

ghc-options:
  

library:
  source-dirs:
    - src

executables:
  test1:
    main: Test1.hs
    source-dirs:
      - test
    dependencies:
      - process-sim

