name:           process-sim
synopsis:       A simulation environment for communicating processes
maintainer:     Stanislav Moiseev <stanislav.moiseev@gmail.com>
copyright:      (C) 2018 Stanislav Moiseev

extra-source-files:
  - README.md

dependencies:
  - ansi-terminal
  - base >= 4.7 && < 5
  - containers
  - free
  - transformers
  - random
  - time

ghc-options:
  - -O2
  - -threaded

library:
  source-dirs:
    - src

executables:
  test1:
    main: test/Test1.hs
    dependencies:
      - process-sim

  test2:
    main: test/Test2.hs
    dependencies:
      - process-sim

